server:
  servlet:
    context-path: /api
  port: 10000
spring:
  application:
    name: api
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,